### ISSUE TITLE
error_log problem OXID CE 6.3.1 / PHP 8.0 / 1.0.26

### ISSUE THREAD

**Issue by tabsl** [mollie/mollie-oxid#12]
exception on module settings tab

OXID Logger.ERROR: Call to undefined function Mollie\Payment\Application\Helper\error_log() ["[object] (Error(code: 0): Call to undefined function Mollie\\Payment\\Application\\Helper\\error_log() at /www/releases/19/vendor/mollie/mollie-oxid/Application/Helper/Payment.php:247)

**Comment by tabsl** [comment]
any news?

**Comment by tabsl** [comment]
error_log was disabled, now it´s working. check if method is available would be fine ;-)

**Comment by FatchipRobert** [comment]
I moved all error_log usages to a new Logger helper.
This Logger helper checks for the existance of a couple of php file-writing functions.
If they are disabled on your server, they wont be used. 
(But there will also be no logged errors then obviously when non of the functions are allowed.)
