### ISSUE TITLE
authorize-then-capture process

### ISSUE THREAD

**Issue by CoolServicesDeV** [mollie/mollie-oxid#18]
As a Scandinavian customer, I expect that I just authorize the credit card payment during the order process. The online shop captures the invoice amount after the order has been dispatched.

In Scandinavia, it is restricted by law that the invoice amount is captured after the order has been dispatched.

Please integrate the authorize-then-capture process into the mollie module for OXID.

**Comment by hwysoszynski** [comment]
Dear author, 

Thanks a lot for your request. 

As Mollie, we currently have the topic of authorisation and capture on our roadmap. Our OXID integration is also planned to get this feature. It will therefore soon be available. As a very rough timeline and to manage expectations, this feature is not expected before Q4 2023. 

Please understand that we cannot give you an exact date for the release, as this is determined by various processes and external dependencies. 

If you have any further questions, please do not hesitate to contact us.
