### ISSUE TITLE
Install module via composer

### ISSUE THREAD

**Issue by thomas-gravel** [mollie/mollie-oxid#3]
If you install the module via composer from your own filesystem the module can't resolve the Mollie\\Api\\ApiClient.

We added alle custom modules and own modules to the directory ./modules/xyz/ (f.e. ./modules/mollie/mollie-oxid)
After that edit the composer.json 
```
"mollie": {
            "type": "path",
            "url": "modules/mollie/*"
},
```

After this you can require the mollie module via composer.
But the missing Class and Namespace send always an error on all payment types.

So if you edit YOUR composer.json 
```
"autoload": {
    "psr-4": {
      "Mollie\\Payment\\": "../../../source/modules/mollie/molliepayment"
    },
    "files":["../../../source/modules/mollie/molliepayment/lib/mollie-api-php/vendor/autoload.php"]
  } 
```

All other could install this via composer...

**Comment by proudcommerce** [comment]
please make this module installable for oxid 6 with standard composer setup

**Comment by FatchipRobert** [comment]
The Mollie Oxid 6 module can now be installed with composer.
Installation formation has been added to the readme.

**Comment by tabsl** [comment]
@FatchipRobert this doensn´t work, because on composer install file in source folder first time is missing ;-)
https://github.com/mollie/mollie-oxid/blob/master/composer.json#L21

**Comment by FatchipRobert** [comment]
@tabsl 
I made 2 Composer test-installations without any problems.
Composer require copies the files to the vendor folder first, then it copies the files to the modules folder and at the very end, the autoloader tasks are executed.

**Comment by FatchipRobert** [comment]
Nevermind.. Oxid obviously changed the order of their composer operations in Oxid 6.2, autoloader generation is now executed before the files are copied to modules folder..
Made more sense before that..
Working on a fix..

**Comment by proudcommerce** [comment]
ok. sorry, we didn´t told you the oxid version number, but it´s 6.2 ;-)

**Comment by FatchipRobert** [comment]
Its fixed now

**Comment by proudcommerce** [comment]
ok. but why don´t you merge the composer files into one?
https://github.com/mollie/mollie-oxid/blob/master/composer.json <-- https://github.com/mollie/mollie-oxid/blob/master/lib/mollie-api-php/composer.json
