### ISSUE TITLE
All payments get deactivated if apply-configuration command is run

### ISSUE THREAD

**Issue by halPlatzke** [mollie/mollie-oxid#5]
if you run `oe:module:apply-configuration` (since Oxid 6.2) All Payments get deactivated.

Problem:
Oxid Applies the Configuration in the following way:
Deactivate Module
Apply Config from Yaml
Activate Module

Since the Mollie Module deactivates all Payments when it is deactivated, all payments stay deactivated after the Configuration is applied.

Fix:
Only Run Query when deactivated from Admin
#4

**Comment by FatchipRobert** [comment]
Issue is fixed in referenced commit
