### ISSUE TITLE
Payment Method Przelewy24

### ISSUE THREAD

**Issue by pvanhemmen** [mollie/mollie-oxid#6]
Hello, is this module capable of processing Przelewy24 paymemts yet? I saw it's defined in the underlying [sdk](https://github.com/mollie/mollie-oxid/blob/master/lib/mollie-api-php/src/Types/PaymentMethod.php), but couldn't find it in the [oxid module structure](https://github.com/mollie/mollie-oxid/tree/master/Application/Model/Payment) itself.

We're thinking about a switch to mollie, but due to our need to also process P24 payments this would hold us off for now. Would it be possible to implement P24 as a payment on your side?

Thanx!

**Comment by FATCHIP-GmbH** [comment]
Hi, 
sorry for the late reply!
We integrate this payment method at the moment and it should be available beginning next week (probably Dec 1st, 2020)

**Comment by pvanhemmen** [comment]
Hi, thank you for your reply. Our customer mentioned he had a positive feedback regarding P24 from mollie, so I think we're all set from December. Thank you for your efforts, it really is the cornerstone for our transition to mollie!

**Comment by markusmichalski-fc** [comment]
Hi! The payment method will be in the next release on Dec 1st, 2020. I now can confirm that 👍 
I will close this issue nowl
