### ISSUE TITLE
Declaration of validatePayment not correct

### ISSUE THREAD

**Issue by kiliankoller** [mollie/mollie-oxid#8]
Hi,
with version 1.0.18 we are seeing the following warning:

[Thu Mar 04 09:15:35.106435 2021] [proxy_fcgi:error] [pid 166059:tid 139828177786624] [client 173.0.81.65:59971] AH01071: Got error 'PHP message: PHP Warning:  Declaration of Mollie\\Payment\\extend\\Application\\Model\\Order::validatePayment($oBasket) should be compatible with OxidEsales\\EshopCommunity\\Application\\Model\\Order::validatePayment($oBasket, $oUser = NULL) in /srv/www/sportschrank_prod/source/modules/mollie/molliepayment/extend/Application/Model/Order.php on line 419'

Regards

**Comment by markusmichalski-fc** [comment]
Hi,
thanks for the information. We will look into it.
Kind regards
